import Head from "next/head";
import Image from "next/image";
import Banner from "../components/Banner";
import FirstSection from "../components/FirstSection";
import Footer from "../components/Footer";
import Header from "../components/Header";
import LargeCard from "../components/LargeCard";
import MediumCard from "../components/MediumCard";
import SmallCard from "../components/SmallCard";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Danbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner />

      {/* Main section custom width */}
      <main className="max-w-7xl mx-auto px-8 sm:px-16 bg-white">
        <SmallCard />
        <MediumCard />
        <LargeCard
          img="https://links.papareact.com/4cj"
          title="The Greatest Outdoors"
          description="Wishlists curated by Danbnb."
          buttonText="Get Inspired"
        />
      </main>

      <Footer />
    </div>
  );
}

//
//
//
//
//

{
  /* Pull data from the server: static render */
}
{
  /* {exploreData?.map((item) => (
            <SmallCard
              key={item.location}
              // img={item.img}
              distance={item.distance}
              location={item.location}
            />
          ))} */
}

//
//
//

// export async function getStaticProps() {
//   // pull JSON array:
//   const exploreData = await fetch("./locations.json", {
//     headers: {
//       "Content-Type": "application/json",
//       Accept: "application/json",
//     },
//   }).then((res) => res.json());

//   return {
//     props: {
//       exploreData,
//     },
//   };
// }
